- name: Criando o diretorio da app Bangu
  file: path={{ item }} state=directory
  with_items: 
    - /opt/bangu
    - /opt/bangu/logs
    - /opt/bangu/conf
  register: criando_diretorios

- name: Copiando o arquivo de deployment da app para o host
  template: 
    src: app-v1.yml.j2
    dest: /opt/bangu/app-v1.yml.j2
    owner: root
    group: root
    mode: 0644
  register: copiando_template

- name: Copiando o arquivo de service da app para o host
  copy: src={{ item.src }} dest={{ item.dest }} 
  with_items: 
    - { src: 'service_app.yml', dest: '/opt/bangu/service_app.yml' }
  register: copiando_service_file
 
- name: Executando o deploy da App bangu
  shell: kubectl apply -f /opt/bangu/app-v1.yml.j2
  register: deploy_app

- name: Criando o service da App Bangu
  shell: kubectl apply -f /opt/bangu/service_app.yml
  register: deploy_svc_app

    
